name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: read

jobs:
  release:
    permissions:
      id-token: write  # needed for PyPI trusted publishing
      contents: read
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-release.yml@c4caf23ade98668434145f5b1abd3bc42cec63e7  # main
