name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: read

jobs:
  release:
    permissions:
      id-token: write  # needed for PyPI trusted publishing
      contents: read
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-release.yml@d2a2353830cf211a9f18f3585085016766294dff  # main
